before:
#  hooks:
#    # you may remove this if you don't use vgo
#    - go mod download
builds:
- main: cmd/vault-plugin-splunk/main.go
  ldflags:
  -  -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.goVersion={{.Env.GOVERSION}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
archives:
- replacements:
    386: i386
  format: zip
  format_overrides:
  - goos: linux
    format: tar.bz2
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Version}}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
